version: "3"
volumes:
  dspacedb-data:
  dspace-webapps:
services:
  builder: 
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    image: dspace:latest
  web:
    command: date
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    image: dspace:latest
    volumes: 
      - .:/dspace
      - ./webapps:/dspace/webapps
    depends_on:
      - db
      - builder
  db:
    build:
      context: .
      dockerfile: containers/db/Dockerfile
    image: postgres:9.6
    environment:
      POSTGRES_DB: dspace
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
    volumes:
      - "dspacedb-data:/var/lib/postgresql/data"
      - "./containers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - "57003:5432"
  tomcat:
    ports:
      - "80:8080"
    image: tomcat:8.5.31
    environment:
      JAVA_OPTS: "-Xmx2000M -Dfile.encoding=UTF-8"
    volumes:
      - .:/dspace
      - ./webapps:/usr/local/tomcat/webapps
    depends_on:
      - web
